/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqlite_netflix;

//import java.sql.PreparedStatement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.util.logging.PlatformLogger;
import java.text.*;  
import javax.swing.JFrame;
//import java.util.*; 
/**
 *
 * @author berka
 */
public class FilmIzle extends javax.swing.JFrame {

    public static long startTime = 0;
    public static long stopTime = 0;
    public static boolean running = false;
    public FilmIzle() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_film = new javax.swing.JLabel();
        jLabel_bolum = new javax.swing.JLabel();
        jLabel_dakika = new javax.swing.JLabel();
        jButton_Bitir = new javax.swing.JButton();
        jButton_Baslat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel_film.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_film.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_film.setText("... FİLMİ İZLENİYOR...");
        getContentPane().add(jLabel_film);
        jLabel_film.setBounds(660, 260, 1120, 51);

        jLabel_bolum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_bolum.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_bolum.setText("KALDIĞINIZ BÖLÜM : ");
        getContentPane().add(jLabel_bolum);
        jLabel_bolum.setBounds(660, 370, 399, 33);

        jLabel_dakika.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_dakika.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_dakika.setText("KALDIĞINIZ DAKİKA :");
        getContentPane().add(jLabel_dakika);
        jLabel_dakika.setBounds(660, 450, 385, 46);

        jButton_Bitir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_Bitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlite_netflix/stop2.png"))); // NOI18N
        jButton_Bitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BitirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Bitir);
        jButton_Bitir.setBounds(270, 410, 210, 180);

        jButton_Baslat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_Baslat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlite_netflix/play1.jpg"))); // NOI18N
        jButton_Baslat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BaslatActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Baslat);
        jButton_Baslat.setBounds(270, 230, 210, 130);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("İzlenen süre : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(660, 550, 385, 110);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FİLMİ BAŞLAT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 260, 180, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FİLMİ KAPAT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 470, 190, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sqlite_netflix/EDIT.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -60, 1960, 1210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BaslatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BaslatActionPerformed
        String combo = (String)Oturum.jComboBox3.getSelectedItem();
        jLabel_bolum.setText("Kaldığınız Bölüm : " + combo);
        String film = Oturum.jTextField2.getText();
        jLabel_film.setText(film + " Adlı Program İzleniyor...");
        String veri_cek = "select kaldigi_dakika from kullaniciprogram where kullanici_id = '"+Giris.username+"' and program_id = '"+film+"'";
        Statement stmt = null;
        //KALDIGI DAKIKAYI VERITABANINDAN ÇEK
        int kaldigiDakika=0;
        try{
            stmt = Sqlite_netflix.conn.createStatement();
            ResultSet rs = stmt.executeQuery(veri_cek);
            while(rs.next()){
                kaldigiDakika = rs.getInt("kaldigi_dakika");
            }
            //rs.close();
        }catch(SQLException e){
            Logger.getLogger(FilmIzle.class.getName()).log(Level.SEVERE,null,e);
        }
        jLabel_dakika.setText("Kaldığınız Dakika : " + Integer.toString(kaldigiDakika));
        
        start();
        
    }//GEN-LAST:event_jButton_BaslatActionPerformed

    private void jButton_BitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BitirActionPerformed
        stop();
        long gecen_sure = getElapsedTime();
        //jLabel4.setText(Long.toString(gecen_sure));
        jLabel4.setText("İzlenen Süre : " + Integer.toString((int)gecen_sure/(1000*60)) + " dakika");
        //gecen_sure=0;
        startTime=0;
        stopTime=0;
        String film = Oturum.jTextField2.getText();
        //String veri_cek = "select kaldigi_dakika from kullaniciprogram where kullanici_id = 'berkan' and program_id = 'Mercan Peşinde'";
        String veri_cek = "select * from kullaniciprogram where kullanici_id = '"+Giris.username+"' and program_id = '"+film+"'";
        Statement stmt = null;
        //KALDIGI DAKIKAYI VERITABANINDAN ÇEK
        int kaldigiDakika=0;
        
        int rate_deger=0;
        try{
            stmt = Sqlite_netflix.conn.createStatement();
            ResultSet rs = stmt.executeQuery(veri_cek);
            
            while(rs.next()){
                rate_deger = rs.getInt("rate");
                kaldigiDakika = rs.getInt("kaldigi_dakika");
            }
            rs.close();
            
            System.out.println("KULLANICI BOYLE BIR PROGRAM IZLEMEMIS");
            
            
            if(rate_deger==0){
                kaldigiDakika+=((int)gecen_sure)/(1000*60);
                try{
                    PreparedStatement pst=null;
                    //pst = conn.prepareStatement("INSERT INTO program values('dsad',null,'aaaa',5,6)");
                    //SimpleDateFormat formatter= new SimpleDateFormat("yyyy-MM-dd");
                    Date date = new Date(System.currentTimeMillis());
                    String tarih = new SimpleDateFormat("yyyy-MM-dd").format(date);

                    pst = Sqlite_netflix.conn.prepareStatement("INSERT INTO kullaniciprogram values(?,?,?,?,?,?,?)");
                    pst.setString(1,Giris.username);
                    pst.setString(2,film);
                    pst.setString(3,tarih);
                    pst.setString(4,Integer.toString((int)gecen_sure/(1000*60)));
                    pst.setString(5,Integer.toString(6));
                    String deger_dondur = (String)Oturum.jComboBox3.getSelectedItem();
                    pst.setString(6,deger_dondur);
                    pst.setString(7,Integer.toString(kaldigiDakika));
                    pst.execute();
                }
                catch(SQLException  e){
                    System.out.println("Error : " + e);
                }
            //
            }
            else{
                //İZLEDİĞİ DAKİKAYI KALDIĞI DAKİKAYA EKLEYİP VERITABANINDA GUNCELLE
                kaldigiDakika+=((int)gecen_sure)/(1000*60);
                String deger_dondur = (String)Oturum.jComboBox3.getSelectedItem();
                String eklenecek = Integer.toString(kaldigiDakika);
                System.out.println("eklenecek " + eklenecek );
                String query = "update kullaniciprogram set kaldigi_dakika = '" + kaldigiDakika + "' where kullanici_id = '"+Giris.username+"' and program_id = '"+film+"'";
                try{
                    PreparedStatement pst = Sqlite_netflix.conn.prepareStatement(query);
                    pst.executeUpdate();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,e);
                }
                String query2 = "update kullaniciprogram set izleme_suresi = '" + ((int)gecen_sure)/(1000*60) + "' where kullanici_id = '"+Giris.username+"' and program_id = '"+film+"'";
                try{
                    PreparedStatement pst = Sqlite_netflix.conn.prepareStatement(query);
                    pst.executeUpdate();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,e);
                }
                String query3 = "update kullaniciprogram set kaldigi_bolum = " + deger_dondur + " where kullanici_id = '"+Giris.username+"' and program_id = '"+film+"'";
                try{
                    PreparedStatement pst = Sqlite_netflix.conn.prepareStatement(query2);
                    pst.executeUpdate();
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,e);
                }
            } 
            
                
            //rs.close();
        }catch(SQLException e){
            Logger.getLogger(FilmIzle.class.getName()).log(Level.SEVERE,null,e);
        }
        
        
        
    }//GEN-LAST:event_jButton_BitirActionPerformed
    public void start() {
        startTime = System.currentTimeMillis();
        running = true;
    }
    public void stop() {
        stopTime = System.currentTimeMillis();
        running = false;
    }
  //elaspsed time in milliseconds
    public long getElapsedTime() {
        long elapsed;
        if (running) {
          elapsed = (System.currentTimeMillis() - startTime);
        } else {
          elapsed = (stopTime - startTime);
        }
        return elapsed;
    }


  //elaspsed time in seconds
  public long getElapsedTimeSecs() {
    long elapsed;
    if (running) {
      elapsed = ((System.currentTimeMillis() - startTime) / 1000);
    } else {
      elapsed = ((stopTime - startTime) / 1000);
    }
    return elapsed;
  }
    /*public static int kronometre(){
        long baslangic = 0;
        long bitis = 0;
        boolean devam = false;
        
    }
    public static int start(long baslangic,boolean devam){
        baslangic = System.currentTimeMillis();
        devam = true;
    }
    public static int stop(long bitis,boolean devam){
        bitis = System.currentTimeMillis();
        devam = false;
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmIzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmIzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmIzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmIzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmIzle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Baslat;
    private javax.swing.JButton jButton_Bitir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_bolum;
    private javax.swing.JLabel jLabel_dakika;
    private javax.swing.JLabel jLabel_film;
    // End of variables declaration//GEN-END:variables
}
